# This is a basic workflow to help you get started with Actions

name: Run Test Script against code on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Libraries
        run: |
          pip install flake8 pytest pytest-cov classes mocker pytest-mock
      
      - name: Checkout Own Repo
        uses: actions/checkout@v2
      
      - name: Checkout Test Script
        uses: actions/checkout@v2
        with:
          repository: zengzihui/DevOps_Oct2021_Team04
          token: ${{ secrets.DEV_REPO }}
      
      - name: Begin Pytest
        run: |
          pytest --cov -v --junitxml=report.xml
      
      - name: Publish Test Script Results
        uses: EnricoMi/publish-unit-test-result-action@v1.24
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report.xml
      
      - if: ${{success()}}
        name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/918820417467199498/9bnSpC3afr6euVolvsCDuNXwM6hUcElqeN5Vl2LDUObNbXEEhWiYV1tlddCHURgHBphV
        uses: Ilshidur/action-discord@master
        with:
          args: 'Test Scripts for {{ EVENT_PAYLOAD.repository.full_name }} successfully passed.'
          
      - if: ${{failure()}}
        name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/918820417467199498/9bnSpC3afr6euVolvsCDuNXwM6hUcElqeN5Vl2LDUObNbXEEhWiYV1tlddCHURgHBphV
        uses: Ilshidur/action-discord@master
        with:
          args: 'Test Scripts for {{ EVENT_PAYLOAD.repository.full_name }} has failed.'
        
